/**
 * CLI Command: memorix init
 *
 * Interactive generator for memorix.yml configuration file.
 * Creates a project-level or user-level memorix.yml with guided prompts.
 */

import { defineCommand } from 'citty';
import * as p from '@clack/prompts';
import { existsSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { homedir } from 'node:os';

export default defineCommand({
  meta: {
    name: 'init',
    description: 'Initialize memorix.yml configuration',
  },
  args: {
    global: {
      type: 'boolean',
      description: 'Create user-level config (~/.memorix/memorix.yml) instead of project-level',
      required: false,
    },
  },
  run: async ({ args }) => {
    p.intro('Initialize Memorix Configuration');

    const isGlobal = !!args.global;
    const targetDir = isGlobal
      ? path.join(homedir(), '.memorix')
      : process.cwd();
    const targetPath = path.join(targetDir, 'memorix.yml');

    // Check for existing file
    if (existsSync(targetPath)) {
      const overwrite = await p.confirm({
        message: `${targetPath} already exists. Overwrite?`,
        initialValue: false,
      });
      if (p.isCancel(overwrite) || !overwrite) {
        p.outro('Cancelled.');
        return;
      }
    }

    // LLM config
    const llmProvider = await p.select({
      message: 'LLM provider (for smart dedup + fact extraction):',
      options: [
        { value: 'none', label: 'None', hint: 'free heuristic mode' },
        { value: 'openai', label: 'OpenAI', hint: 'gpt-4o-mini' },
        { value: 'anthropic', label: 'Anthropic', hint: 'claude-3-haiku' },
        { value: 'openrouter', label: 'OpenRouter', hint: 'multi-provider' },
        { value: 'custom', label: 'Custom', hint: 'OpenAI-compatible' },
      ],
    });
    if (p.isCancel(llmProvider)) { p.outro('Cancelled.'); return; }

    // Embedding config
    const embeddingProvider = await p.select({
      message: 'Embedding provider (for semantic search):',
      options: [
        { value: 'off', label: 'Off', hint: 'BM25 fulltext only' },
        { value: 'api', label: 'API', hint: 'OpenAI-compatible, best quality' },
        { value: 'fastembed', label: 'FastEmbed', hint: 'local ONNX' },
      ],
    });
    if (p.isCancel(embeddingProvider)) { p.outro('Cancelled.'); return; }

    // Git-Memory config
    const gitAutoHook = await p.confirm({
      message: 'Auto-install git post-commit hook for memory capture?',
      initialValue: false,
    });
    if (p.isCancel(gitAutoHook)) { p.outro('Cancelled.'); return; }

    // Behavior config
    const sessionInject = await p.select({
      message: 'Session start injection:',
      options: [
        { value: 'minimal', label: 'Minimal', hint: 'one-line hint (default)' },
        { value: 'full', label: 'Full', hint: 'inject top 5 memories' },
        { value: 'silent', label: 'Silent', hint: 'no injection' },
      ],
    });
    if (p.isCancel(sessionInject)) { p.outro('Cancelled.'); return; }

    // Build YAML content — behavior config ONLY, no secrets
    const lines: string[] = [
      '# memorix.yml — Memorix Configuration',
      '#',
      '# Behavior settings go here. Secrets (API keys) go in .env',
      `# Generated by: memorix init${isGlobal ? ' --global' : ''}`,
      `# Date: ${new Date().toISOString().split('T')[0]}`,
      '',
    ];

    // LLM section
    if (llmProvider !== 'none') {
      lines.push('llm:');
      lines.push(`  provider: ${llmProvider === 'custom' ? 'openai' : llmProvider}`);
      if (llmProvider === 'openai') lines.push('  model: gpt-4o-mini');
      else if (llmProvider === 'anthropic') lines.push('  model: claude-3-haiku-20240307');
      if (llmProvider === 'custom') lines.push('  # baseUrl: http://localhost:11434/v1');
      lines.push('');
    }

    // Embedding section
    lines.push('embedding:');
    lines.push(`  provider: ${embeddingProvider}`);
    if (embeddingProvider === 'api') {
      lines.push('  # model: text-embedding-3-small');
    }
    lines.push('');

    // Git section
    lines.push('git:');
    lines.push(`  autoHook: ${gitAutoHook}`);
    lines.push('  ingestOnCommit: true');
    lines.push('  maxDiffSize: 500');
    lines.push('  skipMergeCommits: true');
    lines.push('  # excludePatterns:');
    lines.push('  #   - "*.lock"');
    lines.push('  #   - "dist/**"');
    lines.push('');

    // Behavior section
    lines.push('behavior:');
    lines.push(`  sessionInject: ${sessionInject}`);
    lines.push('  syncAdvisory: true');
    lines.push('  autoCleanup: true');
    lines.push('  formationMode: active');
    lines.push('');

    // Server section
    lines.push('server:');
    lines.push('  transport: stdio');
    lines.push('  dashboard: true');
    lines.push('  dashboardPort: 3210');
    lines.push('');

    const ymlContent = lines.join('\n');

    // Build .env.example — secrets only
    const envLines: string[] = [
      '# Memorix Environment Variables',
      '# Copy this file to .env and fill in your actual values.',
      '#',
      '# Secrets go here. Behavior settings go in memorix.yml',
      '',
    ];

    if (llmProvider !== 'none') {
      envLines.push('# ── LLM API Key ──');
      if (llmProvider === 'openai' || llmProvider === 'custom') {
        envLines.push('MEMORIX_LLM_API_KEY=sk-your-key-here');
      } else if (llmProvider === 'anthropic') {
        envLines.push('MEMORIX_LLM_API_KEY=sk-ant-your-key-here');
      } else if (llmProvider === 'openrouter') {
        envLines.push('MEMORIX_LLM_API_KEY=sk-or-your-key-here');
      }
      if (llmProvider === 'custom') {
        envLines.push('# MEMORIX_LLM_BASE_URL=http://localhost:11434/v1');
      }
      envLines.push('');
    }

    if (embeddingProvider === 'api') {
      envLines.push('# ── Embedding API Key ──');
      envLines.push('# Falls back to MEMORIX_LLM_API_KEY if not set');
      envLines.push('# MEMORIX_EMBEDDING_API_KEY=sk-your-key-here');
      envLines.push('# MEMORIX_EMBEDDING_BASE_URL=https://api.openai.com/v1');
      envLines.push('');
    }

    envLines.push('# ── Unified Key (optional, fallback for both LLM + Embedding) ──');
    envLines.push('# MEMORIX_API_KEY=sk-your-key-here');
    envLines.push('');
    envLines.push('# ── Compatibility Keys (lowest priority) ──');
    envLines.push('# OPENAI_API_KEY=sk-...');
    envLines.push('# ANTHROPIC_API_KEY=sk-ant-...');
    envLines.push('# OPENROUTER_API_KEY=sk-or-...');
    envLines.push('');

    const envContent = envLines.join('\n');

    // Write files
    mkdirSync(targetDir, { recursive: true });
    writeFileSync(targetPath, ymlContent, 'utf-8');

    // Generate .env.example (and optionally .env)
    if (!isGlobal) {
      const envExamplePath = path.join(targetDir, '.env.example');
      writeFileSync(envExamplePath, envContent, 'utf-8');
      p.log.success(`Created ${envExamplePath}`);

      // Offer to create .env directly
      const envPath = path.join(targetDir, '.env');
      if (!existsSync(envPath)) {
        const createEnv = await p.confirm({
          message: 'Create .env from .env.example? (you can fill in keys later)',
          initialValue: true,
        });
        if (!p.isCancel(createEnv) && createEnv) {
          writeFileSync(envPath, envContent, 'utf-8');
          p.log.success(`Created ${envPath}`);
          p.log.info('Add .env to your .gitignore to keep secrets out of version control.');
        }
      }
    }

    p.log.success(`Created ${targetPath}`);
    console.log('');
    p.log.info('Two files, two roles:');
    p.log.info('  memorix.yml  → behavior settings (what Memorix does)');
    p.log.info('  .env         → secrets only (API keys)');
    console.log('');
    if (gitAutoHook) {
      p.log.info('Git post-commit hook will be auto-installed on next MCP server start.');
    }
    p.outro('Done! Restart your MCP server to apply.');
  },
});
